### ISSUE TITLE
Please enable dwc2 module for USB gadget configuration

### ISSUE THREAD

**Issue by sumpfralle** [silicann/blickwerk-boot#1]
The following guide describes how to specify the details of a USB gadget device: https://www.rmedgar.com/blog/using-rpi-zero-as-keyboard-setup-and-device-definition

There the module "dwc2" is mentioned, which is currently missing in the kernel configuration.

Thank you!

**Comment by vmo69** [comment]
Please see PR #3

**Comment by kmohrf** [comment]
thanks!
